name: 'build-and-deploy-backend-function'
description: 'Build and deploy a backend function to Java 11 runtime'
author: ''
inputs:
  deployer_sa_email:
    description: 'The email address of the IAM service account used for deploying the cloud function'
    required: true
    default: ''
  deployer_sa_key:
    description: 'The IAM service account key used for deploying the cloud function'
    required: true
    default: ''
  func_sa_email:
    description: 'The email address of the IAM service account associated with the function at runtime'
    required: true
    default: ''
  func:
    description: 'The fully specified name of the cloud function'
    required: true
    default: 'backend-function'
  module:
    description: 'Name of the module deployment'
    required: true
    default: 'testrunner'
  entry_point:
    description: 'Name of a Google Cloud Function (as defined in source code) that will be executed'
    required: true
    default: 'bio.terra.cloudfunctions.streaming.GcsBQ'
  runtime_memory:
    description: 'Limit on the amount of memory the function can use (128MB, 256MB, 512MB, 1024MB, 2048MB, 4096MB, and 8192MB)'
    required: false
    default: '256MB'
  bucket:
    description: 'Google Cloud Storage bucket name. Every change in files in this bucket will trigger function execution'
    required: required
    default: ''
  trigger:
    description: 'Specifies which action should trigger the function'
    required: false
    default: 'google.storage.object.finalize'
  project:
    description: 'GCP Project'
    required: true
    default: ''
  region:
    description: 'The Cloud region for the function. Overrides the default functions/region property value for this command invocation'
    required: false
    default: 'us-central1'
  dataset:
    description: 'Name of the BigQuery dataset'
    required: false
    default: 'simple_stream_dataset'
  source:
    description: 'local directory of cloud function source'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    # Set up ADC for cloud function deployment
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ inputs.deployer_sa_email }}
        service_account_key: ${{ inputs.deployer_sa_key }}
        export_default_credentials: true

    - name: Echo Env
      id: echo-envvars
      run: |
        echo ${{ env.GCLOUD_PROJECT }}
      shell: bash
