name: 'build-and-deploy-backend-function'
description: 'Build and deploy a backend function to Java 11 runtime'
author: ''
inputs:
  func:
    description: 'The fully specified name of the cloud function'
    required: true
    default: 'backend-function'
  module:
    description: 'Name of the module deployment'
    required: true
    default: 'testrunner'
  entry_point:
    description: 'Name of a Google Cloud Function (as defined in source code) that will be executed'
    required: true
    default: 'bio.terra.cloudfunctions.streaming.GcsBQ'
  runtime_memory:
    description: 'Limit on the amount of memory the function can use (128MB, 256MB, 512MB, 1024MB, 2048MB, 4096MB, and 8192MB)'
    required: false
    default: '256MB'
  bucket:
    description: 'Google Cloud Storage bucket name. Every change in files in this bucket will trigger function execution'
    required: true
    default: 'testrunner-results'
  trigger:
    description: 'Specifies which action should trigger the function'
    required: true
    default: 'google.storage.object.finalize'
  region:
    description: 'The Cloud region for the function. Overrides the default functions/region property value for this command invocation'
    required: false
    default: 'us-central1'
  dataset:
    description: 'Name of the BigQuery dataset'
    required: true
    default: 'simple_stream_dataset'
  envvars_yml:
    description: 'Full path to a local YAML file with definitions for all environment variables'
    required: false
    default: '/tmp/_envvars_.yml'
runs:
  using: "composite"
  steps:
    - name: Load Environment Variables
      id: load-envvars
      run: |
        cat src/main/resources/testrunner/${{ env.GCLOUD_PROJECT }}/envvars.yml | \
            sed "s|:|=|g" >> $GITHUB_ENV
      shell: bash

    - name: Build Cloud Function
      id: build-step
      run: |
        ./gradlew shadowJar
      shell: bash

    - name: Deploy Cloud Function
      id: deploy-step
      run: |
        gcloud config set project ${{ env.GCLOUD_PROJECT }}
        gcloud functions deploy ${{ inputs.func }} \
          --project=${{ env.GCLOUD_PROJECT }} --region=${{ inputs.region }} \
          --runtime=java11 --entry-point=${{ inputs.entry_point }} \
          --memory=${{ inputs.runtime_memory }} \
          --source=./build/libs \
          --env-vars-file=./src/main/resources/${{ inputs.module }}/envvars.yml \
          --trigger-event=${{ inputs.trigger }}  \
          --trigger-resource=${{ env.GOOGLE_BUCKET }}
      shell: bash

