name: 'create-bq-schemas'
description: 'Create BigQuery Schemas'
author: ''
inputs:
  bigquery-admin-sa-email:
    description: 'The email address of the IAM service account used for creating the BigQuery dataset'
    required: true
    default: ''
  bigquery-admin-sa-key:
    description: 'The IAM service account key used for creating the BigQuery dataset'
    required: true
    default: ''
  schemas-dir:
    description: 'The relative path that contains definitions of BigQuery schema json files'
    required: true
    default: ''
  dataset:
    description: 'Name of the BigQuery dataset'
    required: true
    default: ''
  project:
    description: 'GCP Project'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    # Configure ADC for cloud function deployment
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_email: ${{ inputs.bigquery-admin-sa-email }}
        service_account_key: ${{ inputs.bigquery-admin-sa-key }}
        export_default_credentials: true

    - name: Create BigQuery schemas
      id: create-schemas-step
      run: |
        gcloud config set project ${{{ inputs.project }}
        bq show ${{ inputs.dataset }} || bq mk ${{ inputs.dataset }}
        for i in ${{ inputs.schemas-dir }}/*.json; do
            [ -f "$i" ] || break
            TBL=$(basename ${i%.json})
            bq show --schema ${{ inputs.project }}:${{ inputs.dataset }}.${TBL} || \
                bq mk --table ${{ inputs.project }}:${{ inputs.dataset }}.${TBL} $i
        done
      shell: bash
