# This workflow will build a backend cloud function with Gradle
# For more information see: https://github.com/google-github-actions/deploy-cloud-functions

name: Build and deploy backend cloud function

on:
  push

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up AdoptOpenJDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.gradle') }}
          restore-keys: v1-${{ runner.os }}-gradle-${{ hashfiles('**/gradle-wrapper.properties') }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Cloud Function
        id: build-step
        run: |
          ./gradlew shadowJar
          ls -l build/libs
          ls /opt/hostedtoolcache

      - uses: google-github-actions/setup-gcloud@master # Set up ADC for credentials
        with:
          service_account_email: ${{ secrets.DEPLOY_CF_SA_EMAIL }}
          service_account_key: ${{ secrets.DEPLOY_CF_SA_KEY_JSON }}
          export_default_credentials: true

      - name: Deploy Cloud Function
        id: deploy-step
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: gcs-bq-function
          runtime: java11
          entry_point: bio.terra.cloudfunctions.streaming.GcsBQ
          memory_mb: 512MB
          source_dir: ./build/libs
          project_id: terra-kernel-k8s
          event_trigger_type: providers/cloud.storage/eventTypes/object.finalize
          event_trigger_resource: projects/_/buckets/terra-kernel-k8s-testrunner-results/objects/*
