# This workflow is used to deploy GCP cloud functions from prebuilt jar files located at dsp-artifact-registry
# For more information see: https://github.com/google-github-actions/deploy-cloud-functions

name: Deploy Cloud Functions from prebuilt jars

on:
  push

jobs:
  deploy-from-prebuilt-jars:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up ADC for credentials
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.DSP_CF_STAGE_SA_EMAIL }}
          service_account_key: ${{ secrets.DSP_CF_STAGE_SA_KEY }}
          export_default_credentials: true

      # Pull the Prebuilt Jars
      - name: Stage Cloud Functions Archive in project dsp-artifact-registry under bucket cloudfunctions-dsp-artifact-registry
        id: stage-cloud-functions-archive-step
        run: |
          # Make a random directory under /tmp to store the Jars
          LIBS=$RANDOM
          mkdir -p /tmp/$LIBS
          rm -fr /tmp/$LIBS/*
          ls -l /tmp/$LIBS | wc -l
          gsutil cp gs://cloudfunctions-dsp-artifact-registry/terra-gcs-bq-streaming-functions-0.0.1-SNAPSHOT-all.zip /tmp/$LIBS
          unzip /tmp/$LIBS/terra-gcs-bq-streaming-functions-0.0.1-SNAPSHOT-all.zip
          ls -l /tmp/$LIBS
