# This workflow is used to deploy GCP cloud functions from source
# For more information see: https://github.com/google-github-actions/deploy-cloud-functions

name: Deploy Cloud Functions from source

on:
  push

jobs:
  deploy-from-source:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up ADC for accessing GCS bucket cloudfunctions-dsp-artifact-registry
      # The vault path for this secret is secret/dsde/terra/cloudfunctions/cloudfunctions-publisher-sa
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.DEPLOY_CF_SA_EMAIL }}
          service_account_key: ${{ secrets.DEPLOY_CF_SA_KEY_JSON }}
          export_default_credentials: true

      # Deploy cloud function from the prebuilt Jar from download-prebuilt-jars-step
      - name: Deploy the TestRunner backend function
        id: deploy-testrunner
        uses: ./.github/actions/build-and-deploy-backend-function
        with:
          func: gcs-bq-function
          module: testrunner
          entry_point: bio.terra.cloudfiletodatastore.testrunner.cloudfunctions.TestRunnerStreamingFunction
          runtime_memory: 512MB
          trigger: google.storage.object.finalize
          source: .
