# This workflow is used to deploy GCP cloud functions from source
# For more information see: https://github.com/google-github-actions/deploy-cloud-functions

name: Test deploy

on:
  push

jobs:
  deploy-from-source:

    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: DEV
    steps:
      - uses: actions/checkout@v2

      - name: Configure secrets, SA, Project ID
        id: config-step
        run: |
          DEPLOYER_SA_KEY=$(echo -n ${{ secrets[format('{0}_TESTRUNNER_CF_DEPLOYER_SA', env.ENVIRONMENT)] }} | base64 -d)
          DEPLOYER_SA_EMAIL=$(echo -n $DEPLOYER_SA_KEY | jq -r .client_email)
          PROJECT_ID=$(echo -n $DEPLOYER_SA_KEY | jq -r .project_id)
          STREAMER_SA_KEY=$(echo -n ${{ secrets[format('{0}_TESTRUNNER_STREAMER_SA', env.ENVIRONMENT)] }} | base64 -d)
          STREAMER_SA_EMAIL=$(echo -n $STREAMER_SA_KEY | jq -r .client_email)
          echo $DEPLOYER_SA_EMAIL
          echo $STREAMER_SA_EMAIL
          echo ::set-output name=deployer-sa-email::$DEPLOYER_SA_EMAIL
          echo ::set-output name=deployer-sa-key::$DEPLOYER_SA_KEY
          echo ::set-output name=project-id::$PROJECT_ID
          echo ::set-output name=streamer-sa-email::$STREAMER_SA_EMAIL

      # Deploy cloud function from the source
      - name: Deploy the TestRunner streamer function
        id: deploy-testrunner
        uses: ./.github/actions/build-and-deploy-backend-function
        with:
          deployer_sa_email: ${{ steps.config-step.outputs.deployer-sa-email }}
          deployer_sa_key: ${{ steps.config-step.outputs.deployer-sa-key }}
          func_sa_email: ${{ steps.config-step.outputs.streamer-sa-email }}
          func: gcs-bq-function
          module: testrunner
          entry_point: bio.terra.cloudfiletodatastore.testrunner.cloudfunctions.TestRunnerStreamingFunction
          runtime_memory: 512MB
          trigger: google.storage.object.finalize
          project: ${{ steps.config-step.outputs.project-id }}
          bucket: ${{ steps.config-step.outputs.project-id }}-testrunner-results
