# This workflow is used to deploy GCP cloud functions from source
# For more information see: https://github.com/google-github-actions/deploy-cloud-functions

name: Test GHA Secrets

on:
  push

jobs:
  deploy-from-source:

    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: DEV
    steps:
      - uses: actions/checkout@v2

      - name: Get GitHub secrets
        id: github-secrets-step
        run: |
          DEPLOYER_SA_KEY=$(echo -n ${{ secrets[format('{0}_TESTRUNNER_CF_DEPLOYER_SA', env.ENVIRONMENT)] }} | base64 -d)
          DEPLOYER_SA_EMAIL=$(echo -n $DEPLOYER_SA_KEY | jq -r .client_email)
          STREAMER_SA_KEY=$(echo -n ${{ secrets[format('{0}_TESTRUNNER_STREAMER_SA', env.ENVIRONMENT)] }} | base64 -d)
          STREAMER_SA_EMAIL=$(echo -n $STREAMER_SA_KEY | jq -r .client_email)
          echo $DEPLOYER_SA_EMAIL
          echo $STREAMER_SA_EMAIL
          echo ::set-output name=deployer-sa-email::$DEPLOYER_SA_EMAIL
          echo ::set-output name=deployer-sa-key::$DEPLOYER_SA_KEY
          echo ::set-output name=streamer-sa-email::$STREAMER_SA_EMAIL
